#!/usr/bin/bash

img="$1"
selection="$2"
CACHE_DIR="$HOME/.cache/wal/schemes/"

base=$(basename "$img")
cache="$CACHE_DIR/$base.json"

if [ -f "$cache" ]; then
  wal --theme "$cache" >/dev/null
else
  wal -i "$img" --cols16 darken --contrast 3.0 --saturate 0.7 -n >/dev/null
fi

pkill -9 waybar && waybar & && sleep 0.2 # SIGUSR1 will cause waybar to core dump :/
pkill -SIGUSR1 swaync && sleep 0.4
notify-send -i preferences-system "Theme updated" "System theme was updated to \"$selection\""
