#!/usr/bin/bash

img="$1"
selection="$2"
CACHE_DIR="$HOME/.cache/wal/schemes/"

base=$(basename "$img")
cache="$CACHE_DIR/$base.json"

if [ -f "$cache" ]; then
  wal --theme "$cache" >/dev/null
else
  wal -i "$img" --cols16 darken --contrast 3.0 --saturate 0.7 -n >/dev/null
fi

pkill -9 waybar && waybar & # SIGUSR1 will cause waybar to core dump :/
sleep 0.2
swaync-client --reload-css
python3 ~/.config/wallpapers/rmpc.py -t theme.ron
notify-send -i preferences-system -t 2500 "Theme updated" "System theme was updated to \"$selection\""
