#!/bin/bash

case "$1" in
  wifi)
    if [  "$(nmcli radio wifi)" = "enabled" ]; then
      nmcli radio wifi off
    else
      nmcli radio wifi on
    fi
    ;;

  bluetooth)
    if bluetoothctl show | grep -q "Powered: yes"; then
      bluetoothctl power off
    else
      bluetoothctl power on
    fi
    ;;
esac
